/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-124081-gd4cf7cf1cf-20260422"
#endif /* AVUTIL_FFVERSION_H */
